### ISSUE TITLE
Common Average Rereferenceing as a Substiture for Low-Pass Filtering?

### ISSUE THREAD

**Issue by djsoper** [MouseLand/Kilosort#166]

**Comment by djsoper** [comment]
I've been wondering for a while how Kilosort2 avoids the high frequency noise without explicitly using a Low-Pass filter at 7000hz or so. I just realized it substitutes a Low-Pass filter for a Common Average Re-reference. Hopefully you can clear this up for me, because I'm amazed that doesn't cause loss of units as they happen across channels or cause lots of noise to get propagated throughout the data. Considering this works in Neuropixel electrodes, which have a pretty good SNR, I'm guessing the effects on the data aren't as bad as I imagine them to be, but I'm still a bit lost. Can someone explain to me why using CAR on electrodes with contacts <60 microns apart wouldn't ruin the potential spiking activity seen across channels? 

That being said, can I easily infiltrate the pipeline and replace the CAR with a low-pass so that I'm not worried about this or do you foresee that causing issues for your sorting algorithm?

Thanks,
Dan

**Comment by marius10p** [comment]
In my experience, high-passing never really helped, unless you have some very high-frequency noise or something. This was also true of algorithms not based on template matching, because a common first step is to project the spikes onto a set of principal components, which are typically smooth. This means the projection roughly achieves a low-passing as well. 

Moving on to template matching algorithms and Kilosort2, we've observed that low-passing actually significantly hurts. This is because spikes do have a significant amount of power at high-frequencies, which can increase the SNR of the template match. Now, you might ask how come the high-frequency noise doesn't hurt us in this case and the answer has to do with wavelets. A hand wavy explanation is that wavelets are very specific spatiotemporal filters, so they can reject most of the noise after thresholding.

I'm sure there are better mathematical explanations for this effect, but the empirical result for me has always been that low-passing hurts. 

The CAR is a different problem, and it's in fact more similar to channel whitening, which we also do. That also has a big effect, because any waves that are big on many channels are typically noise, and only the sharp features of waveforms are really useful. Of course, if you have lots of channels, the CAR won't really eat into your spike variance and will mostly remove the synchronized noise, but even for fewer channels it should only have the same effect as whitening. Anyway, to avoid small Nchannels effect, we always advise people to process the entire experiment together, even if the channels have no chance of cross-talk,.

**Comment by djsoper** [comment]
Thank you very much for your thorough response! I hadn't thought of the PCA as a method by which to Low-Pass Filter, but it makes sense to me. I'll have to do a little more digging to understand wavelets, but it's nice to know that the noise isn't seemingly impactful. 

The CAR problem (and I'm not sure how impactful whitening is in this vein) still stands in my mind. Full Disclosure: we are doing intracranial experiments in humans with novel electrodes, so our use case is not perfect for this algorithm. A worry for me is that we are often manipulating the brain condition (e.g. cold saline, methohexital) which might introduce new baselines and create new waveforms/lose waveforms after a CAR. Do you think that these issues are avoidable with CAR? I'm also wondering about how you draw the line for "lots of channels." Our typical micros, which have the same contact distance as the neuropixel but a much higher SNR, have only 128 channels. Is that enough to mitigate the spike variance degradation? Is there an easy way to stop the whitening to see how impactful it is on our end spike products?

Thanks again for your very helpful response!
-Dan

**Comment by marius10p** [comment]
128 channels should definitely be enough.
