### ISSUE TITLE
Slightly inconsistent batch reordering in runs with identical parameters

### ISSUE THREAD

**Issue by dimokaramanlis** [MouseLand/Kilosort#187]
Hi Marius,

I've run KS2 on the same dataset couple of times with the same parameters, and I noticed that the total number of units or the results in phy are slightly different each time. We realized that the batch distances-reordering were slightly different in each run, so I tried to look deeper to where this inconsistency might come from.

While random number generation is controlled in all parts of the code (through rng(1)), random numbers are not controlled on the GPU:
https://github.com/MouseLand/Kilosort2/blob/67a42a87b866b6150385a46eec358adb349d9ff2/preProcess/initializeWdata2.m#L17

After controlling the seed on the GPU (through gpurng), we were still getting different results. We then realized that the output (idchan) of a cuda function, mexThSpkPC.cu, was slightly different in each run:

https://github.com/MouseLand/Kilosort2/blob/67a42a87b866b6150385a46eec358adb349d9ff2/preProcess/extractPCbatch2.m#L41

Graphics card is RTX 2080 Ti. Is this inconsistency a known issue? Does it have to do with precision limitations of the GPU?

**Comment by marius10p** [comment]
Thanks for bringing that up and for figuring out that the gpuArray randn has a different seed, I will take a look at that mex function when I have time and let you know what I find. 

There is also randomness in the main optimization after batch re-ordering (if you start with the same batch order). @jenniferColonell and I spent a long time trying to track down the origins. We managed to reduce the problem (some bugs in asynchronous GPU calls), but not eliminate it. That randomness accumulates with the number of iterations, which is why I suspect it is somehow chaotically amplified from floating point conversions. Or there's a bug we still haven't identified. 

However, the iterative amplification should not apply to batch reordering, so maybe we can at least fix that one.
