### ISSUE TITLE
exclude time periods from template extraction

### ISSUE THREAD

**Issue by agbondy** [MouseLand/Kilosort#189]
Hi Marius -- I am doing phototagging experiments with Neuropixels probes. The idea is to tag ChR2-expressing cells by periodically photostimulation during the recording. However, the photostimulation creates brief periods during the recording that pose a challenge for spike sorting: the photo-electric effect creates artifacts and cells fire at high rates with waveforms that sometimes do not perfectly match any templates from outside the stimulation period.  It occurred to us that one useful approach would be to only perform the spike sorting on the periods without photostimulation and then apply those templates to the photostimulation periods to find matching spikes. This avoids the common problem of sorters finding lots of clusters that only spike during photostimulation. Here we'd just be identifying spike times of events that suitably match a cluster that is also identified outside of photostimulation.

It's easy enough to chop out of the data during photostimulation and run Kilosort but we aren't sure how to then apply the templates Kilosort finds to find matches during the interleaved photostimulation periods. I know you probably don't have time to find a custom solution to this, but we thought there might be a discrete bit of the Kilosort code already written which basically does this last bit. "runTemplates" seems to do something somewhat like this maybe? Any pointers you can provide would be great! Thanks!

Adrian

**Comment by marius10p** [comment]
hi Adrian, sorry for the slow response. I don't think a solution along those lines is simple, because Kilosort makes fixed size batches early on, and then all the processing steps happen on each batch as a whole. Have you thought of subtracting out the average photoelectric effect? I'd be curious how well that works.

**Comment by agbondy** [comment]
Hi Marius -- Yes, getting rid of the photoelectric artifact is pretty easy. I basically just zero-out the data during the periods when the photoelectric artifact is happening. That works very well. The issue I'm highlighting here is distinct -- the shape of photostimulation-induced spikes can be slightly distinct from those normally produced by a neuron. I worry that this may lead Kilosort to artifically split clusters. However, I'm less concerned about this after initial tests. So long as you make batches large relative to the photostimulation periods things look OK. If the batches are not big relative to the photostimulation periods, then some batches are dominated by photostimulation  periods and the time-reordering sticks those batches together (i.e. it thinks the recording is drifting in a distinct way when photostimulation is occurring). That's obviously not good.

**Comment by marius10p** [comment]
This could be due to the filtering and whitening steps, or due to the relaxation dynamics post-stimulation. Do you see the changes specifically in the spike shape, or is there a clear voltage dynamic irrespective of spikes? If the latter, it might help to subtract out the average post-stimulation voltage trace from each channel before any other preprocessing happens.

**Comment by agbondy** [comment]
I don't know the answer to your question. I will have to look into this. Thanks.
