### ISSUE TITLE
Preprocessing introduces noise - and artifacts in clustering

### ISSUE THREAD

**Issue by rivlinoa** [MouseLand/Kilosort#222]
Hi,
I have a problem trying to use Kilosort2 on my data, I am not sure what I do wrong, any insight would be welcome!

I am recording with neuropixels 3A probe. 
My data suffers from some high frequency noise so I apply the SpikGLX Glb Dmx CAR before running Kilosort2. The raw data looks pretty good after this CAR. 
I run Kilosort2 with default parameters. 

I notices that the filtered data after Kilosort2 preprocessing is much noisier than my raw data, and I don't think it should look this way. Moreover, there are events detected by the algorithm as (low amplitude) spikes, but when looking at the raw data there is nothing there. Those artifacts  are contaminating clusters with healthy spikes, as spikes and noise are ofter classified as belonging to the same cluster.

I attach a picture of traces (raw, filtered, prediction) from Kilosort2 GUI for refrence. I highlighted some 'atrifct spikes' that are not visible in the raw data, but there are more of them... 

Many thanks in advance!
Noa

![Kilosort2GUI](https://user-images.githubusercontent.com/20164106/89728773-71c54980-da38-11ea-82ce-ca965d713b5d.PNG)

**Comment by nsteinme** [comment]
I don't think the traces after filtering are truly noisier - I think
instead they are just increased in scale (for some reason) in the gui.
There are hotkeys to change the scaling so you can set the green traces to
have peak spike amplitudes more similar to the black and I think you will
see that the SNR looks similar.

I would recommend in general to simply exclude units that are found with
amplitude that is too small to be sorted with high quality. You didn't show
evidence that these super-low-amplitude units are part of otherwise good
units, and that shouldn't be the case - could you show what you're looking
at when you say that?

**Comment by rivlinoa** [comment]
Thank you very much Nick for the fast and helpful reply!
It is much appreciated!!!

I am glad to hear that my filtered data is just increased in scale :)

As for the sorting, I attach pieces from phy GUI of 3 different units (there are more that display the same issue). In the trace view I see good spikes, and some noise-level fluctuations that are classified as the same unit. In examples #1 and #2 you can see that the correlogram displays noise-like periodicity.
The distribution over time of all units makes sense to me since I reduced anesthesia levels during the recording. 
It is hard for me to say whether a unit is dominated by noise or by reliable spikes, or determine the level of contamination within a unit. Either way missing spikes because they are clustered into a noise unit, or introducing noise into a good unit is undesirable in high rates. Any tip on how to evaluate it would be great!

Do you think that setting a higher threshold for the initial pass of the sorting would help getting rid of the super-low-amplitude identified spikes? Any other solution comes to your mind?

![Slide1](https://user-images.githubusercontent.com/20164106/89761360-de068280-daf6-11ea-85cd-113b2c21fcae.PNG)
![Slide2](https://user-images.githubusercontent.com/20164106/89761361-df37af80-daf6-11ea-9fe8-d5587708396c.PNG)
![Slide3](https://user-images.githubusercontent.com/20164106/89761362-dfd04600-daf6-11ea-865d-c5467848630d.PNG)


Thanks again, 
Noa

**Comment by nsteinme** [comment]
Yes, I think all of those three examples are just noise/MUA. Note that
sometimes you can see a good-looking spike highlighted blue in traceview
even when the unit is very low amplitude noise, because a good spike
happened by chance at the same time one of these noise events was detected.
I would just post-hoc throw out the clusters with amplitudes that are too
low.

**Comment by rivlinoa** [comment]
Thanks for the advice! It is very helpful. 
I will just drop the low amplitude units. 

Just to make sure - you mean that the good-looking spikes that happen to occur at the same time as the noise events are probably detected as well and clustered as a different unit?

**Comment by nsteinme** [comment]
Yes, there's nothing to prevent KS from finding two different spikes that
happened right at the same time. So knowing that one cluster had a spike at
time t does not imply that every other cluster did NOT have a spike at time
t.
