### ISSUE TITLE
ContamPct and automatic assignment to Good or Mua

### ISSUE THREAD

**Issue by ruxyb2004k** [MouseLand/Kilosort#242]
Hello,

I would like to get more information about how each cluster is automatically assigned a Good or Mua label. Is it related to ContamPct? I noticed in my analysis that all Good clusters have a ContamPct < 10, although in a different Issue here, someone was saying they have a threshold of 20. Still, there are also Mua clusters with ContamPct = 0, so maybe there is an exception to the rule. 
Can I somehow change the rule of the assignment (for example to set a threshold of 20) or would it be a terrible idea? 

Thanks.

**Comment by marius10p** [comment]
This entirely depends on how you are going to use the spike sorted data, and how much your application is robust to errors in spike sorting. If you benefit from more units, and it doesn't introduce a confound, I'd say go for it. 

I am not sure why a MUA cluster would have ContamPct < 10, since that was the only metric we used. In the latest version, we also use the spatial spread of the unit (too large and it's definitely noise).
