### ISSUE TITLE
Is temp_wh.dat file necessary for Phy2?

### ISSUE THREAD

**Issue by HiroyukiKato7** [MouseLand/Kilosort#311]
Hi,

I saw in #101 that temp_wh.dat is not necessary for Phy and can be deleted after sorting.  However, when I run Phy2 on the Kilosort2.5 data, it throws an error saying that "(temporary file path)/temp_wh.dat does not exist" and it fails to load Waveform View.  

My understanding was that temp_wh.dat is a temporary file during sorting, and I wrote a script to delete it once sorting is done.  I used to run Kilosort1 and Phy2 on different computers, but do I now need to run them on the same PC and run Phy2 before temp_wh.dat is overwritten by the next sorting session?

Maybe I'm misunderstanding something.  It would be great if you could guide me on the right workaround for this issue.

Thanks!

**Comment by marius10p** [comment]
Since v2.5, the params.py file points to the temporary dat by default, because that file has been drift corrected (and channel whitened and high-pass filtered), so it makes it easier to interpret the results. For example, a cluster that may seem to be very broad and poorly isolated before drift correction, can suddenly become very good after drift correction, if the dispersion of its spikes was primarily due to drift. 

You can also pass rezToPhy2 a third input (anything really, just pass ```1```) and then it will point to the original binary file. You can also just manually replace the path in params.py after the fact.

**Comment by HiroyukiKato7** [comment]
Thanks for your prompt response!  I wrote a script so that temp_wh.dat is copied to the same directory as the original data and edited rezToPhy so that params.py now points to temp_wh.dat with a relative path.  Now I can see the Waveform View. 

One strange thing is that, regardless of which cluster I select, the Waveform View always have flat traces at the second-top and second-bottom positions, whereas I don't see any issue in the Trace View (please see the attached image).  The flat lines are always in these positions regardless of whether I select a cluster in a shallow channel or deep channel.  Is this a normal behavior after the drift correction?  Or, am I still messing up something?

![WaveformView](https://user-images.githubusercontent.com/45468166/106400681-e2e52880-63ed-11eb-884c-2adc27444832.PNG)

**Comment by marius10p** [comment]
It's not normal, and I haven't seen that behavior, maybe @rossant has an idea?

**Comment by HiroyukiKato7** [comment]
The flat line issue was somehow resolved by changing the scaling of WaveformView by Shift+up/down.  It's usable by simple adjustment, so it's not a big problem, but maybe this is a bug of Phy2?
