### ISSUE TITLE
features view cannot load it phy.

### ISSUE THREAD

**Issue by WeissShahaf** [MouseLand/Kilosort#317]
features view cannot load it Phy. 
it did for KS 2.5

**Comment by aarac** [comment]
Yes, I had the same issue. Is it a "save for phy" issue where pc_features.npy file is not saved?

**Comment by rajatsaxena** [comment]
In the `final_clustering` routine in the `main_kilosort` script, I noticed that 

```
rez1.cProj = [];
rez1.iNeigh = [];
rez1.cProjPC = [];
rez1.iNeighPC = [];
```

`rez1 `then gets returned as `rez`.

`rezToPhy2` (used to store output to Phy format) skips storing feature related npy cause it is empty.

**Comment by metmic** [comment]
Hi Marius, great work overall. However, is there any timeline when the feature and amplitude views are coming back for kilosort 3 anytime soon? I am very much relying on these during curation in phy. For now I still have to use KS 2, because KS 2.5 always gives me an assertion error. My NPIX recordings contain lots of internal high frequency noise, so I preprocess the data prior to loading it into KS (band pass filtering, setting those channels that don't show spiking activity to NaN). Thanks

**Comment by WeissShahaf** [comment]
any news on when we can expect to see PC features for phy again?

i'm getting 4-5 good units, and 100 mua's that i cannot split because i have no PCA space to do it in.

thanks,
shahaf

**Comment by pabloslash** [comment]
Any updates on this feature? Very much needed. Thanks!

**Comment by nataliekoh** [comment]
Bump! Any updates on this?

**Comment by WeissShahaf** [comment]
Kilosort no longer uses the features. But u could compute them yourself
from the raw data, given the timestamps of the spikes.
Then format it so phy can read it.

I'd be happy to know if anyone already has a script for that.




Shahaf Weiss, PhD

Max Planck Institute for Brain Research

NSK - Laurent department
Max-von-Laue-Str. 4
60438 Frankfurt am Main, Germany
www.brain.mpg.de

***@***.***

***@***.***

Tel:+49 17657814689

**Comment by moscraciunxxx** [comment]
@tianw6 - that was a nice suggestion!
