### ISSUE TITLE
Many clusters contaminated by noise

### ISSUE THREAD

**Issue by TomBugnon** [MouseLand/Kilosort#417]
Hi all,
@marius10p , you mention [here](https://github.com/cortex-lab/KiloSort/issues/141#issuecomment-399469121) that contamination by noise is often not an issue. However a lot of my clusters seem poorly isolated from noise in my data, with legitimate high-amplitude spikes pooled with "spikes" that totally look like noise to me in the preprocessed data.
I really need to avoid false-positive spikes for the type of analysis I'm intending to do and thus end up marking the clusters as noise and dismissing a lot of legitimate spikes.

Here's an example of such a cluster, detected by kilosort2.5 with default parameters:
the waveform view and autocorrelogram look good
![image](https://user-images.githubusercontent.com/14128078/123128979-e1270a80-d44b-11eb-95f4-2e5262ca48e3.png)
But there are both legit high-amplitude spikes and what looks to me like noise in the traceview (I'd say around half/half for this cluster)
![image](https://user-images.githubusercontent.com/14128078/123129074-f4d27100-d44b-11eb-84b4-73b0ccef6792.png)
![image](https://user-images.githubusercontent.com/14128078/123129323-29462d00-d44c-11eb-9655-545ba2d5725e.png)
![image](https://user-images.githubusercontent.com/14128078/123130666-3b749b00-d44d-11eb-9d4f-264b6bd0db70.png)

I tried increasing the threshold (to Th=[12,8]) and lambda (to 40), which somewhat helps but doesn't really solve the issue.

I understand that kilosort thresholds the projection of raw data over the template, such that some spikes with low amplitude might be detected if they match the template well, but I would still expect (mistakingly?) the spikes detected by KS to look like spikes to the human eyes.

Thanks in advance for any suggestion!
Tom

**Comment by czuba** [comment]
Hey @TomBugnon,

I've rewritten significant portions of Kilosort in my ["ks25" fork](https://github.com/czuba/Kilosort) of the repo. One of the things that really helped improve the usability of my sorting outputs has been a tightening of the range of samples used for template projection to exclude the more extraneous/noisy samples in the tails.

_Specifically, waveform feature & amplitude projections are computed on samples 6:(nt0-16);_ with the standard 61 sample waveform, that corresponds to a 40 sample projection range (1.0 ms @40kHz, 1.333 ms @30kHz).

Although this leaves the template tails essentially unconstrained, I haven't seen any wacky behavior from them (...reinforcing the notion that it really is mostly noise). Furthermore, this ~1 ms waveform projection is equal to or greater than anything that I would normally use for traditional hand-sorting, and in my hands really seems to have improved the specificity of template & feature projections (both w/in Kilosorting operations, and in the amplitude outputs used by Phy).

Since those edits are largely confined to a few sample indices in the [CUDA functions](https://github.com/czuba/Kilosort/tree/ks25/CUDA) & w/in Kilosort functions that call them, it should be a pretty straightforward task to compile & plug those **"_pcTight"** versions into your existing/preferred Kilosort codebase.

-Thad.

**Comment by TomBugnon** [comment]
Hi @czuba thank you so much, I haven't responded and still haven't tried your version but will do!
