### ISSUE TITLE
rezToPhy2 isn't writing real channel map

### ISSUE THREAD

**Issue by akel123** [MouseLand/Kilosort#537]
The original channel map is being replaced by a vector 0:nChans-1 when converting to phy2 (or phy).

https://github.com/MouseLand/Kilosort/blob/d55179f4bed45d4f17e5481283bc3f260212c1c7/utils/rezToPhy2.m#L152-L154

Is this expected behavior?

**Comment by zm711** [comment]
Hey @akel123 

Yes. Those are just the indices of the channel map which can be arbitrary (Matlab is 1 indexed and Python is 0, so that's where the change comes from). The important values are in the next line of the code:

```matlab
 writeNPY([xcoords ycoords], fullfile(savePath, 'channel_positions.npy'));
```
This is where the "real positioning" of the electrodes is saved.  So if you want to do a depth based center of mass weighting you would use the ycoords info (either in Matlab or Python). 

Or to put this another way the channel map is made of three parts for each electrode:

```
[map_index, xcoord, ycoord] 
```

e.g. [1, 0, 50] or something of that sort. The map_index just keeps track of the identities of the xcoords and the ycoords. 

Does that help?

**Comment by akel123** [comment]
Hi @zm711 

Thanks for the explanation. Just a couple follow up questions:

1) I could be missing it, but from what I see in the code, the `xcoords` (nor `xc`) are never permuted by `chanMap`. So how do we know which row of the recording a certain `xcoords[i]` is referencing? Unless `channel_map.npy` isn't actually the channel map, but rather the indices for the original channel map, which could be what you mean.

2) I did notice that the preprocessed data has the channel map already applied (in gpuFilter):
https://github.com/MouseLand/Kilosort/blob/d55179f4bed45d4f17e5481283bc3f260212c1c7/preProcess/gpufilter.m#L16-L19
Then this row-permuted data appears to be written to disk
https://github.com/MouseLand/Kilosort/blob/d55179f4bed45d4f17e5481283bc3f260212c1c7/preProcess/preprocessDataSub.m#L102-L114
Meaning that `temp_wh.dat` has rows of ascending channel idxs (perhaps columns because of the transpose, but I'm just going to refer to them as rows for simplicity) whereas in the original `raw_data.bin` file this isn't necessarily the case.  
So if I wanted to know which rows corresponded between `temp_wh.dat` and `raw_data.bin`, I wouldn't be able to rely on the `channel_map.npy` output from rezToPhy2, I'd have to reference the original channel map that I fed as input to kilosort?

Thanks,

Aaron

**Comment by zm711** [comment]
<img width="350" alt="Screenshot 2023-04-13 at 16 55 19" src="https://user-images.githubusercontent.com/92116279/231880757-7c1e1808-0ff9-48cc-b0f5-73ca9f805a9f.png">

No worries. So when you enter the channel map into Kilosort you give three vectors (see above) as an example we will say you have a tetrode 

  4
2  3
  1:

X-coords [20, 0, 40, 20]
Y-coords [0, 20, 20, 40]
Indices [1,2,3,4]

The key for your raw data is to know that the first row of your raw data matrix is 1, then 2, then 3, then 4. So when you put in the channel map you give the indices in the order of the matrix 1,2,3,4, but you alter the x-coords and the y-coords to be the real positioning of the electrodes in real life. You could also technically make the indices 2,3,1,4 but then you would have to correct the x vector and y vector to work. 

So the data will still be organized with 1,2,3,4 but to translate that to real data you need to have put in the correct x and y positioning. If you want some more visualization of probe to amplifier for creating channels maps you should check out:
https://github.com/SpikeInterface/probeinterface, which helps auto map neuronexus and CambridgeNeurotech probes for you.

So to answer your final question `channel_map.npy` by itself is only 1/3 of the info you need. If you also do

```python
coords = np.load('channel_positions.npy')
x_coords= coords[:,0]
y_coords = coords[:,1]
indices = np.load('channel_map.npy')
```

indices[0] would be the index pointing to the real x position x_coords[0] and the real y position y_coords[0] which in our example would be 20, 0.

For a good example of how to use this data in Matlab (in case you aren't a huge python fan) I would advise looking at this function from Cortex-Lab (where Kilosort 1 was written). 

https://github.com/cortex-lab/spikes/blob/master/analysis/getWaveForms.m
https://github.com/cortex-lab/spikes/blob/master/preprocessing/phyHelpers/loadKSdir.m


Finally, when Kilosort runs if it determines that channel 1 is bad (on our tetrode example). It will delete it from the channel map and so it will instead write [2,3,4], because it didn't actually use the channel for info and both Phy and you need to know this for your post-hoc analysis.

Hope that clears it up a bit. Happy to try to help more if I can.

**Comment by zm711** [comment]
> Thanks for the explanation. Just a couple follow up questions: I could be missing it, but from what I see in the code, the xcoords (nor xc) are never permuted by chanMap. So how do we know which row of the recording a certain xcoords[i] is referencing? Unless channel_map.npy isn't actually the channel map, but rather the indices for the original channel map, which could be what you mean.

Just to be clear. This is exactly what I was saying. They use a better name in the Matlab code.

`chanMap0ind` makes it explicit that these are indices for the channel map.

**Comment by akel123** [comment]
> X-coords [20, 0, 40, 20]
> Y-coords [0, 20, 20, 40]
> Indices [1,2,3,4]
>
> The key for your raw data is to know that the first row of your raw data matrix is 1, then 2, then 3, then 4. So when you put in the channel map you give the indices in the order of the matrix 1,2,3,4, but you alter the x-coords and the y-coords to be the real positioning of the electrodes in real life. You could also technically make the indices 2,3,1,4 but then you would have to correct the x vector and y vector to work.

 
So I guess my point is that if I gave as input instead (adjusting x/y vectors according to shuffled indices):
X-coords [0, 40, 20, 20]
Y-coords [20, 20, 0, 40]
Indices [2,3,1,4]

Then my rez2Phy output will be 
```python
coords = np.load('channel_positions.npy')
x_coords= coords[:,0]                 # [0, 40, 20, 20] 
y_coords = coords[:,1]                # [20, 20, 0, 40]
indices = np.load('channel_map.npy')  # [1, 2, 3, 4]
```
Which is a little strange because the `x_coords` and `y_coords` are still in the order `[2, 1, 3, 4]`, but `channel_map.npy` being `[1, 2, 3, 4]` would suggest they are not. 

> Finally, when Kilosort runs if it determines that channel 1 is bad (on our tetrode example). It will delete it from the channel map and so it will instead write [2,3,4], because it didn't actually use the channel for info and both Phy and you need to know this for your post-hoc analysis.

This example also gives a bit unintuitive output (at least for me), because what would be written is
```python
coords = np.load('channel_positions.npy')
x_coords= coords[:,0]                 # [0, 40, 20] 
y_coords = coords[:,1]                # [20, 20, 40]
indices = np.load('channel_map.npy')  # [1, 2, 3]
```
and I would think the `channel_map.npy` that should be written is `[2, 3, 4]` as opposed to `[1, 2, 3]`, since those are the channels that `x_coords` and`y_coords` correspond to.

**Comment by akel123** [comment]
> > Thanks for the explanation. Just a couple follow up questions: I could be missing it, but from what I see in the code, the xcoords (nor xc) are never permuted by chanMap. So how do we know which row of the recording a certain xcoords[i] is referencing? Unless channel_map.npy isn't actually the channel map, but rather the indices for the original channel map, which could be what you mean.
> 
> Just to be clear. This is exactly what I was saying. They use a better name in the Matlab code.
> 
> `chanMap0ind` makes it explicit that these are indices for the channel map.

I suppose if we interpret `chanMap0ind` in this way, then all is well. But defining `chanMap0ind = [1:Nchan]-1` doesn't really offer any additional information to the output. And in other areas of the matlab code `chanMap0ind = chanMap - 1`, but it's only when writing to phy that it's redefined as the former.

In my opinion, it's still more clear to write `channel_map.npy` as the original `chanMap` zero-indexed

**Comment by zm711** [comment]
>I suppose if we interpret chanMap0ind in this way, then all is well. But defining chanMap0ind = [1:Nchan]-1 doesn't really offer any additional information to the output. And in other areas of the matlab code chanMap0ind = chanMap - 1, but it's only when writing to phy that it's redefined as the former.

Actually I mis-wrote it is just the indices. The channel map is just indices of the raw data. I opened some real data and the bad channels are stored internally, but not given in `channel_map.npy` or `channel_position.npy`. Channel map is just zero-indexed indices and then position are the positions. So this function is where they generate the internal `igood`, but I double checked with real data and it is never returned.

https://github.com/MouseLand/Kilosort/blob/d55179f4bed45d4f17e5481283bc3f260212c1c7/preProcess/get_good_channels.m

**Comment by zm711** [comment]
The reason why it needs `rez.ops.Nchan` instead of `chanMap` is because you can optionally disconnect electrodes, which will hard save `chanMap` missing channels. Whereas Nchan is saved as the total number of rows in your raw data matrix (ie the true indices of the data) (obtained from the `chanMap` you enter pre-removal of disconnected electrodes).

**Comment by akel123** [comment]
> > I suppose if we interpret chanMap0ind in this way, then all is well. But defining chanMap0ind = [1:Nchan]-1 doesn't really offer any additional information to the output. And in other areas of the matlab code chanMap0ind = chanMap - 1, but it's only when writing to phy that it's redefined as the former.
> 
> Actually I mis-wrote it is just the indices. The channel map is just indices of the raw data. I opened some real data and the bad channels are stored internally, but not given in `channel_map.npy` or `channel_position.npy`. Channel map is just zero-indexed indices and then position are the positions. So this function is where they generate the internal `igood`, but I double checked with real data and it is never returned.
> 

The main problem I see is that `channel_map.npy` will always be the vector `[1:Nchan]-1`; however, `channel_positions.npy` retains the original channel map (with the disconnected channels omitted). So if you use a chanMap with a different order than `1, 2, 3, 4...` the `channel_positions.npy` file will have the `x/ycoords` out of order. I haven't looked at the phy code of how the coordinates are determined, but the only information it could possibly look at to order them would be the values in `channel_map.npy`, which would be incorrect. 

To be clear, the channels in `temp_wh.dat` are permuted to be in ascending idx order, so in terms of accessing accurate waveforms, there's no problem (unless you are using the un-preprocessed data as your rec source). I guess the only problem would be the channel positions only if you used a channel map that's not `1, 2, 3, 4...`. This could be fixed by re-indexing `x/y/kcoords` by `chanMap` before writing them, and that may be the simplest way. 

That said, it would also be nice to have some record of the original channel map in the `rezToPhy2` output in my opinion (if only to know how the original `.bin` data is ordered without having to read the `chanMap.mat` matlab file).

**Comment by akel123** [comment]
> The reason why it needs `rez.ops.Nchan` instead of `chanMap` is because you can optionally disconnect electrodes, which will hard save `chanMap` missing channels. Whereas Nchan is saved as the total number of rows in your raw data matrix (ie the true indices of the data) (obtained from the `chanMap` you enter pre-removal of disconnected electrodes).

Just a side note on this: it looks like `rez.ops.Nchan` is the number of connected channels (these are the only data written to `temp_wh.dat`) and `rez.ops.NchanTOT` is what keeps track of the total channels in the original raw `.bin` data file:
https://github.com/MouseLand/Kilosort/blob/d55179f4bed45d4f17e5481283bc3f260212c1c7/preProcess/preprocessDataSub.m#L34-L38

**Comment by akel123** [comment]
the x/ycoords should probably be re-indexed in the preprocessing step because they're used for local whitening:
https://github.com/MouseLand/Kilosort/blob/d55179f4bed45d4f17e5481283bc3f260212c1c7/preProcess/get_whitening_matrix.m#L62-L68

https://github.com/MouseLand/Kilosort/blob/d55179f4bed45d4f17e5481283bc3f260212c1c7/preProcess/whiteningLocal.m#L1-L14

If we're using a channel map that isn't `1,2,3,4...`, that whitening procedure won't really work as intended, at least from what I'm seeing.

**Comment by zm711** [comment]
I mean except for the case of a dead channel the map should always be `1,2,3,4...` since the matrix of data will always just be nChannels x mSamples (where we just label the rows from 1 up to n). Even in the case of a dead channel if all values are 0 then the covariance or the whitening shouldn't matter. Don't have time to check if this is pre or post the connected channel step. I will say from experience if I try to delete a matrix channel (by deleting a row in the amplifier matrix) manually in matlab and then update the map (in the x vector and y vector to remove the electrode), kilosort just fails.

**Comment by akel123** [comment]
Ok with the supposition of channel map always being `1,2,3,4...` that makes sense. Feel free to close the issue. Thanks!

**Comment by kingsEffy** [comment]
so...channel id  = chanMap(i), where i is picked from  int32([1:rez.ops.Nchan]), ?
