### ISSUE TITLE
Unable to perform assignment because the size of the left side is 16-by-6-by-5795 and the size of the right side is 16-by-3-by-5795.

### ISSUE THREAD

**Issue by vknorman** [MouseLand/Kilosort#559]
Hi everyone,

I keep getting the following error when I use kilosort:
Unable to perform assignment because the size of the left side is 16-by-6-by-5795 and the size of the right side is 16-by-3-by-5795.

Error in trackAndSort (line 206)
    fWpc(:, :, irange) = gather(featPC); % PC features

Error in ksGUI/runSpikesort (line 801)
                [obj.rez, st3, tF]     = trackAndSort(obj.rez);

Error in ksGUI/runAll (line 634)
            obj.runSpikesort;

Error in ksGUI>@(~,~)obj.runAll() (line 321)
                'Callback', @(~,~)obj.runAll());
 
Error while evaluating UIControl Callback.

I have not encountered this error with previous data sets, so I am confused why I am seeing it now. Thank you!

**Comment by jessiburd** [comment]
I am having the similar issue except the error message is slightly different. Did you ever figure out what was going wrong here?

This is my error message:

Unable to perform assignment because the size of the left side is 32-by-3-by-2810 and the
size of the right side is 32-by-6-by-2810.

Error in trackAndSort (line 196)
    fWpc(:, :, irange) = gather(featPC); % PC features

Error in runTemplates (line 34)
[rez, st3, fW,fWpc] = trackAndSort(rez, iorder);

Error in learnAndSolve8b (line 39)
rez         = runTemplates(rez);

Error in main_kilosort (line 45)
rez = learnAndSolve8b(rez, iseed);

**Comment by ClaudiaJou** [comment]
Same issue here!

Unable to perform assignment because the size of the left side is 16-by-6-by-582 and the size of the right side is 16-by-3-by-582.

Did you ever figure it out?
Thanks!

**Comment by kingsEffy** [comment]
I had this issue as well, try to lower ops.ntbuff see whther it helps, this solved mine~
