### ISSUE TITLE
BUG: OE 384 chan recordings are not loaded properly in the GUI

### ISSUE THREAD

**Issue by FernandoSn** [MouseLand/Kilosort#605]
### Describe the issue:

It seems that neuropixels 1.0 data acquired with Open Ephys (384 channels) is not properly loaded in the GUI. Something similar happens in previous versions when you tell the GUI explicitly that you have 385 channels when you do have 384, there is an offset and you get some lines across the visualization heatmap. Even when I explicitly tell the GUI that I have 384 channels, the artifact does not go away. This does not happen with SpikeGLX "385 channel" recordings. To be able to properly sort my OE data, I concatenated a zero after my last channel to create an "extra channel"  and have a total of 385. This seemed to work so far.

Before appending zeros (384 channels)
![beforeAppendingzeros384channs](https://github.com/MouseLand/Kilosort/assets/47955351/a562459d-5169-4b6c-bc6b-7b4aeb9be0b5)

After appending zeros (385 channels)
![afterAppendingzeros385channs](https://github.com/MouseLand/Kilosort/assets/47955351/6837a888-4803-4466-b441-31db7b9a0405)

### Version information:

Windows server 2019, python 3.9

**Comment by marius10p** [comment]
@jacobpennington this is similar to issue #604. The GUI is not updating the number of channels behind the scenes for some reason.

**Comment by jacobpennington** [comment]
@FernandoSn I just want to check that I'm correctly understanding the steps you're taking. This is what I get if I use the GUI with some data that I've truncated from 385 to 384 channels:

1) After data is loaded, which defaults to 385 channels because of the probe layout:
![image](https://github.com/MouseLand/Kilosort/assets/35777376/fcadf83c-cf76-4002-aae4-e05a001da34e)

2) After changing the number of channels. The plot will still have the artifact at this point:
![image](https://github.com/MouseLand/Kilosort/assets/35777376/e4dc77f6-e2ff-458a-b793-23a5e06a37e7)

3) After clicking "Load" again to reload the data with the new settings (artifact gone):
![image](https://github.com/MouseLand/Kilosort/assets/35777376/fc88a1cb-af49-4c48-9105-1d198b93d8ae)

You're doing all 3 of those things and still seeing the diagonal artifact? If so, would you be able to send a small snippet of data that I could investigate this with?

**Comment by jacobpennington** [comment]
Please let us know if you continue to have issues with this after the changes I mentioned above.
