### ISSUE TITLE
Kernel size problem running kilosort4

### ISSUE THREAD

**Issue by alejoss30** [MouseLand/Kilosort#610]
### Describe the issue:

Im trying to run kilosort4 using this

```
from kilosort import run_kilosort, DEFAULT_SETTINGS
DEFAULT_SETTINGS['fs'] = 20000
settings = DEFAULT_SETTINGS
# ( path to drive if mounted: /content/drive/MyDrive/ )
settings['data_dir'] = '/content/drive/MyDrive/ArielSleep/preprocessed'
settings['n_chan_bin'] = 64

ops, st, clu, tF, Wall, similar_templates, is_ref, est_contam_rate = run_kilosort(settings=settings, probe= p)
```

but after working for a couple of minutes, it gives me back the following error:

`RuntimeError: Calculated padded input size per channel: (60). Kernel size: (61). Kernel size can't be greater than actual input size`

Would apreciate any ideas on how to solve this problem. Thanks.

**Comment by jacobpennington** [comment]
Hello,
Are you able to post the full traceback for the error?

**Comment by alejoss30** [comment]
Hi, sure.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-52-a2afa65e7222> in <cell line: 9>()
      7 settings['n_chan_bin'] = 64
      8 
----> 9 ops, st, clu, tF, Wall, similar_templates, is_ref, est_contam_rate = run_kilosort(settings=settings, probe= p)

3 frames
/usr/local/lib/python3.10/dist-packages/kilosort/run_kilosort.py in run_kilosort(settings, probe, probe_name, filename, data_dir, file_object, results_dir, data_dtype, do_CAR, invert_sign, device, progress_bar, save_extra_vars)
    142 
    143     # Sort spikes and save results
--> 144     st, tF, _, _ = detect_spikes(ops, device, bfile, tic0=tic0,
    145                                  progress_bar=progress_bar)
    146     clu, Wall = cluster_spikes(st, tF, ops, device, bfile, tic0=tic0,

/usr/local/lib/python3.10/dist-packages/kilosort/run_kilosort.py in detect_spikes(ops, device, bfile, tic0, progress_bar)
    401     clu, Wall = clustering_qr.run(ops, st0, tF, mode='spikes', device=device,
    402                                   progress_bar=progress_bar)
--> 403     Wall3 = template_matching.postprocess_templates(Wall, ops, clu, st0, device=device)
    404     print(f'{clu.max()+1} clusters found, in {time.time()-tic : .2f}s; ' +
    405             f'total {time.time()-tic0 : .2f}s')

/usr/local/lib/python3.10/dist-packages/kilosort/template_matching.py in postprocess_templates(Wall, ops, clu, st, device)
     81 
     82 def postprocess_templates(Wall, ops, clu, st, device=torch.device('cuda')):
---> 83     Wall2, _ = align_U(Wall, ops, device=device)
     84     #Wall3, _= remove_duplicates(ops, Wall2)
     85     Wall3, _, _ = merging_function(ops, Wall2.transpose(1,2), clu, st[:,0],

/usr/local/lib/python3.10/dist-packages/kilosort/template_matching.py in align_U(U, ops, device)
     68     Uex = torch.einsum('xyz, zt -> xty', U.to(device), ops['wPCA'])
     69     X = Uex.reshape(-1, ops['Nchan']).T
---> 70     X = conv1d(X.unsqueeze(1), ops['wTEMP'].unsqueeze(1), padding=ops['nt']//2)
     71     Xmax = X.abs().max(0)[0].max(0)[0].reshape(-1, ops['nt'])
     72     imax = torch.argmax(Xmax, 1)

RuntimeError: Calculated padded input size per channel: (64). Kernel size: (65). Kernel size can't be greater than actual input size
```

Thats the full error. Thanks.

**Comment by jacobpennington** [comment]
Hello,

First, it looks like that's not actually the same error, or maybe was run on different data? The input & kernel sizes are not the same. I only bring that up because the first case (input size 60) means an empty variable since a padding of 30 is added to either end of the input, whereas the numbers in the second one you posted indicate something else going on. And if both are happening on different runs with the same data and settings, well... that's another problem.

Second, the traceback does help narrow things down, but there are still several possible causes. Would you be able to share your probe file and some sample data so I can debug this further?

**Comment by jacobpennington** [comment]
My e-mail is jacob.p.neuro@gmail.com, if you're able to share a file/link there. Or just let me know if there's some other way we can do that.

**Comment by jacobpennington** [comment]
@marius10p I found the problem, but I'm not sure what the best solution would be. The error is happening because this line in `get_data_cpu` (line 330 in `clustering_qr.py`) always returns an `ix` that is all False, since the latter part of the and statement is never true.
```
    ix = torch.logical_and(torch.abs(xy[1] - y0) < dmin, torch.abs(xy[0] - x0) < dminx)
```
Which is happening because the probe looks like this:
![image](https://github.com/MouseLand/Kilosort/assets/35777376/e5e55097-96a8-4127-a8ba-59131ba3ed82)
So `x0` is around 100, and `dminx` is around 20, so it doesn't find any nearby channels. since there's that large gap in the middle.

Setting `dminx` to something much larger, like 100, will get past the error and finish sorting, but the results look odd and it's not clear to me if that's because of this issue, or if the data is just noisy. I see several spots in the data like this, for example, that look like possible recording artifacts that could throw off the results:
![image](https://github.com/MouseLand/Kilosort/assets/35777376/05891dd0-01ef-417a-8716-de0a66975cac)

**Comment by jacobpennington** [comment]
Also @alejoss30  I noticed the data is `uint16`, so you would need to specify `run_kilosort(..., data_dtype='uint16')` unless you're converting the data to 'int16' elsewhere.

**Comment by marius10p** [comment]
@jacobpennington I think the correct solution here is indeed to set dminx (and probably dmin too) manually which should work fine. We cannot automatically deal with cases like this. This information should go in the readthedocs somewhere...

**Comment by jacobpennington** [comment]
Let us know if you continue to have issues with this. Another suggestion we've given for multi-shank probes, as a temporary work-around, is to artificially stack the shanks on top of each other in the probe geometry, so that the lateral spacing is not an issue. That will likely work better than increasing `dminx` for this case.
