### ISSUE TITLE
Value Error never found suitable channels

### ISSUE THREAD

**Issue by Neuronanc** [MouseLand/Kilosort#617]
### Describe the issue:

Trying to run KS4 on data collected with NPX2.0 probe. Channel map generated in SGLXMetaToCoords in matlab.

Here is a screen shot of the error I get in the message log box. Any assistance is greatly appreciated!

![Screenshot 2024-03-12 174124](https://github.com/MouseLand/Kilosort/assets/72527577/4b42c8d4-5dab-4902-a0bb-1d6f2531d233)

**Comment by jacobpennington** [comment]
Hi @Neuronanc. Try setting `dminx` (in the "extra settings" menu) to something like 75 or 100, and play around with it from there. This sets the lateral spacing between template centers, which is hard to determine automatically for probes with large gaps between contacts.

**Comment by Kayv-cmb** [comment]
Hi @jacobpennington, 
I have exactly the same error with the neuropixel 2.0 4shanks, I tried to play around 100 with dminx, but below a 100 it failed because of the issue and higher than a 100, 0 cluster are detected and the drift computed is around 700um(which seem way too big). Do you have an idea with which parameter on top dminx I can play to be able to sort?

**Comment by marius10p** [comment]
Hello, unfortunately we do not yet have the capability to process shanks separately, which would be necessary here. 

Until we add that, I recommend that you stack your channels vertically on top of each other, rather than horizontally. You can add a small amount of space between segments (like 100um, but it's probably fine for 20um too). This should not really matter very much. You will probably get results close to as good as if the shanks were properly processed in parallel.

**Comment by Kayv-cmb** [comment]
Hello, I tried several parameters and if I put dmin or dminx at 500 (if I go to a thousand I have no cluster), I have a sorting that is almost similar to my result with ks2-5 and ks3, and the drift is also similar. Can you provide some info on what those parameters are used for? and some explanation on why they are important?(I can't figure it out)

Also stacking the shanks vertically seems to work, thank you for your advice.

**Comment by jacobpennington** [comment]
There are short descriptions for all the parameters in the gui, if you mouse-over the name of the parameter for about half a second. You can find the same information in [kilosort.parameters.py](https://github.com/MouseLand/Kilosort/blob/main/kilosort/parameters.py).

When universal templates are created for the initial spike detection step, `dminx` determines how far apart the centers of those templates are spaced laterally, tiling the geometry of the probe based off the smallest and largest values of 'xc' (or 'yc', for 'dmin'). So for example, if the smallest `xc` is 0 and the largest is 1000 and `dminx = 500`, then in `kilosort.spikedetect.template_centers`:
```
nx = np.round((xmax - xmin) / (dminx/2)) + 1
ops['xup'] = np.linspace(xmin, xmax, int(nx))
```
the lateral positions of the template centers (`ops['xup']`) will be set at 0, 250, 500, 750, 1000. Ideally you want all of those center positions to overlap the positions of the contacts (we're working on adding readthedocs pages to explain this better). More ideally, you'd want 3 or 4 of those templates spread out for each column of contacts which is what stacking the shanks will accomplish (as well as avoiding putting all/most of the template centers in the empty spaces between shanks).

**Comment by jacobpennington** [comment]
Closing this for now, please let us know if you encounter more issues with this. I'll just reiterate that the suggestion we've settled on is to stack the shanks in the probe layout instead of adjusting `dminx`.

**Comment by carlacodes** [comment]
Is there a python/code implementation of stacking the shanks or do you need to use the GUI for this? 

> Closing this for now, please let us know if you encounter more issues with this. I'll just reiterate that the suggestion we've settled on is to stack the shanks in the probe layout instead of adjusting `dminx`.

**Comment by jacobpennington** [comment]
@carlacodes You could use the probe creation tool in the GUI, but you don't need to. There's no single way to do it since it depends on your probe, you're just creating a new .mat or .prb. Feel free to share your probe file if you need help creating the stacked version.

**Comment by jacobpennington** [comment]
@carlacodes I don't know how SpikeInterface interacts with Kilosort4, so I don't know if that's a possibility or not, you would have to ask the SpikeInterface team. However, if you install the latest version of Kilosort4 the shank stacking should no longer be necessary. See https://github.com/MouseLand/Kilosort/releases/tag/v4.0.4.

**Comment by carlacodes** [comment]
@jacobpennington great thank you very much, does this mean that a default dminx = 32 will work on multi shank probes?

**Comment by jacobpennington** [comment]
@carlacodes The default should work, yes, but you might want to consider changing it if your contact spacing is substantially different. Ideally `dminx` should be the median horizontal distance between contacts, but small differences there shouldn't impact the results too much. For example, using `dminx = 24` with a Neuropixels 1 probe (instead of 32) results in a ~3% change in spike and unit count for me.

If you want to see exactly how it's affecting things, you can look at the probe in the Kilosort4 GUI.  You don't need to load the data or run sorting there if you don't want to do that, but it will let you preview the probe and see where templates are being placed. This is what that looks like for a Neuropixels 1 probe with `dminx = 32`:
![image](https://github.com/MouseLand/Kilosort/assets/35777376/a4285b92-a836-4c7b-b501-2120b92c1ec3)
The universal templates (white dots) are meant to tile the space of the probe, such that each contact (green squares) should have a handful of templates centered around it. Compare that to using `dminx = 100` for the same probe:
![image](https://github.com/MouseLand/Kilosort/assets/35777376/0ed5ad53-4880-45d1-a135-d78060c68875)
The contacts in the middle of the shank have no nearby templates, so that will have a big impact on the sorting.
