### ISSUE TITLE
having difficulty converting .ncs file to .bin

### ISSUE THREAD

**Issue by fffllllxxxxxxxx** [MouseLand/Kilosort#618]
### Describe the issue:

i tired 'select file' and it goes like a)(the directory name is invalid); and i tried 'select folder' and it goes like b) 
![image](https://github.com/MouseLand/Kilosort/assets/89821536/e42b1b8b-d933-44df-ad30-93c362452d90)
![image](https://github.com/MouseLand/Kilosort/assets/89821536/01bc79ca-2021-4af7-9a1a-5ccdf599689e)
need hlep!!

**Comment by fffllllxxxxxxxx** [comment]
Hi,
hope this could help. btw i am using win11, would that be a problem?
![717c23a89665e0df79e85c7976fadfe](https://github.com/MouseLand/Kilosort/assets/89821536/9cf3e2a9-7a1f-4b3f-836c-8095aabb8504)
![735098eef9c011a16072a4319915a38](https://github.com/MouseLand/Kilosort/assets/89821536/776607a7-bcf9-458d-85e2-435f1075d0ed)

**Comment by jacobpennington** [comment]
Hello,

This looks like it's related to a known issue with Neo (a library that spikeinterface relies on for file io) and Cheetah (I'm guessing that's for handling Neuralynx recordings). There's an issue posted here with some suggested solutions:
https://github.com/SpikeInterface/spikeinterface/issues/2007

The short version is it looks like the pypi-installed version of SpikeInterface doesn't have a fix for it yet, but you can reinstall Neo and SpikeInterface from source to fix the issue according to @zm711.

**Comment by zm711** [comment]
Yeah we recently update neo with a bunch of neuralynx fixes, but they keep changing their file format so we are fighting quite the battle to make sure all files work. You'll need to install neo from source for the header fixes. Spikeinterface from source will help with segment gaps. But definitely open an issue on neo if it doesn't work so we can fix it asap :)

**Comment by fffllllxxxxxxxx** [comment]
hi, 
bad news. i reinstall neo and spikeinterface from source and it still looks like this

![image](https://github.com/MouseLand/Kilosort/assets/89821536/3938356c-1dcc-4d97-92fb-335257307909)

Through exploration, I only found .npy file, which then converted into .bin files with numpy(data type int16), can be loaded and showed in kilosort.

I am quiet a beginner and didn't really know what to do now..

**Comment by zm711** [comment]
@fffllllxxxxxxxx, you can definitely open an issue over on Neo (I'm not sure if Kilosort wants an unrelated issue on their issue tracker), but the error you are getting now is that you are suppose to put in your directory and not the file and you gave it the file. So instead you should input:

`c:/Users/Felix/Desktop/elec/2017-08-23_09-42-01/2017-08-23_09-42-01`. Basically neuralynx scans the directory for the files rather than just load one file. It should autodetect the presence of the .ncs file. Could you try again feeding it the directory and if that still fails I would say open an issue on Neo so we can troubleshoot over there rather than here :)

**Comment by jacobpennington** [comment]
@fffllllxxxxxxxx Are you saying you're not sure what to do in the Kilosort gui? If so, here are the basic steps to get started. We'll be adding a readthedocs page soon that goes over this with screenshots.

1. Click "select binary file" near the top-left, under the big "LOAD" button.
2. Navigate to your .bin file in the file dialog that pops out.
3. Click the drop-down menu under "Select Probe Layout" a few rows down. Select "[new]" to create a new probe file, or "other..." to select one that you've already created. [Look here](https://kilosort.readthedocs.io/en/latest/tutorials/make_probe.html) for guidance on creating probe files.
4. Update settings as needed for your data. For example, you might need to change "number of channels", "sampling frequency", or "Data dtype" if the defaults don't match your data.
5. Click the big "LOAD" button.
6. Look at the data in the heatmap on the right, make sure there aren't big diagonal lines or other obvious artifacts.
7. Click "Run", near the bottom of the left-hand side of the GUI.

**Comment by jacobpennington** [comment]
I'm going to close this since the original issue was addressed. Please let us know if you need more help using the software. The readthedocs page I mentioned isn't live yet, but you can see a [preview of it here](https://github.com/MouseLand/Kilosort/blob/docs_update/docs/gui_guide.rst) if you want more detailed instructions. The screenshots links aren't working yet, but they should be uploaded soon.
