### ISSUE TITLE
BUG: filtered signal and prediction not aligned properly in v3.0.1 GUI

### ISSUE THREAD

**Issue by teristam** [MouseLand/Kilosort#623]
### Describe the issue:

After upgrading to v3.0.1, the filtered signal and prediction are not aligned to each other in time. The problem goes away when downgraded back to v3.0

![image](https://github.com/MouseLand/Kilosort/assets/3406709/3ecf0e44-4060-4236-9cfb-a913736deb31)

### Version information:

kilosort: v3.0
Matlab: R2021a

### Experiment information:

Neuropixel 1.0

**Comment by marius10p** [comment]
I'll take a look when I have time. 3.0.1 fixes the spike holes bug. Hopefully it did not introduce a time alignment bug. 

Could you please double check if this is also a problem for release 2.5.1? The same modification was made there.

**Comment by teristam** [comment]
Hi,

I think I can also observe a similar thing in v2.5.1:

<img width="695" alt="image" src="https://github.com/MouseLand/Kilosort/assets/3406709/a2f0853f-7ada-4b5b-a3b2-efa98172970f">

**Comment by teristam** [comment]
Just some more updates on the investigation. I am using the first 100s of a recording for testing. The first 2s of data seem to look fine, but the alignment problem starts to appear after the 2.3s point.

**Comment by marius10p** [comment]
Yeah, there is a difference in how the first batch is treated for the buffer offsets. What I have to determine is if the spike times are correct (and the GUI is wrong) or viceversa. In practical terms it should be a difference of 2-3ms.

**Comment by zm711** [comment]
@alejoe91, it looks like this our issue too. I'm just going to copy your message below so we can work off this thread instead

> @marius10p

[zm711](https://github.com/zm711) and I noticed that the bug fix branches (at least for KS2.5) is fixing the spike holes, but there seem to be a misalignment with the spike times, so that the extracted waveforms don't look right. See this [example](https://figurl.org/f?v=npm://@fi-sci/figurl-sortingview@12/dist&d=sha1://06238ba4129b26d825f23f1a2d67241c9f0aa307&s=%7B%22sortingCuration%22:%22gh://AllenNeuralDynamics/ephys-sorting-manual-curation/main/ecephys_717374_2024-03-15_15-10-01/experiment1_Record%20Node%20101%23Neuropix-PXI-100.46116_recording1/kilosort2_5/curation.json%22%7D&label=ecephys_717374_2024-03-15_15-10-01%20-%20experiment1_Record%20Node%20101%23Neuropix-PXI-100.46116_recording1%20-%20kilosort2_5%20-%20Sorting%20Summary&zone=aind): the auto/cross correlograms (bottom right) look correct, but the waveforms are just noise.

Any idea where the misalignment could take place?

**Comment by alejoe91** [comment]
I think that the spike times are wrong since the waveforms extracted externally are also wrong. So I suppose that rules out this being a GUI problem

**Comment by marius10p** [comment]
I have fixed both bugs that were causing the spike holes problem. I think the spike times are correct now, can you please check it in version 3.0.2 (new release)?

**Comment by teristam** [comment]
> I have fixed both bugs that were causing the spike holes problem. I think the spike times are correct now, can you please check it in version 3.0.2 (new release)?

Hello, I haven't tested the new changes in kilosort3 yet because I am trying to get kilosort4 to work. However, I noticed even in the latest version of kilosort4 (4.0.4), the spike time does not seem to align with the index from the BinaryFiltered file (bfile). I assume the index in the bfile corresponds to the actual data index in the original data?

I used the following code to extract spikes directly from the bfile

```
clu_id = 3
s = []

chan_best = (templates**2).sum(axis=1).argmax(axis=-1)
chan_best = chan_map[chan_best]

cb = chan_best[clu_id]

spk_t = st[clu==clu_id]

for i in range(80):
    t = spk_t[i] 
    s.append(bfile[(t-bfile.nt//2):(t+bfile.nt//2+1),:])
s = np.stack(s)
```
I noticed the extracted waveforms are mixed:

![image](https://github.com/MouseLand/Kilosort/assets/3406709/a7de1eb4-f08c-449d-9a1a-6f0bef85ef62)

but when I subtract bfile.nt from the spike time, it works:
![image](https://github.com/MouseLand/Kilosort/assets/3406709/f2cf9165-6a88-4c2a-8a9e-cb7692a9c995)

And then spike time from the 2nd batch onward don't seem to need this time shift:

![image](https://github.com/MouseLand/Kilosort/assets/3406709/a87f4113-751d-42e7-94b6-73280b76f3dd)

Since the spike time is extremely important for analysis, may be more rigorous tests should be implemented?
