### ISSUE TITLE
BUG: Kilosort4 saves amp and Amplitude values by changing them.

### ISSUE THREAD

**Issue by hoyeon912** [MouseLand/Kilosort#632]
### Describe the issue:

![Screenshot from 2024-03-26 18-33-41](https://github.com/MouseLand/Kilosort/assets/96232889/a06b7fca-3ac2-4002-83b8-d21432050950)
This screenshot is captured from Kilosort4 files

![Screenshot from 2024-03-26 18-33-53](https://github.com/MouseLand/Kilosort/assets/96232889/13f4f7be-fe1d-40b7-8b7c-441cd0402d96)
and this one is from Kilosort2.5 files

Kilosort4 saves amp value in Amplitude and vice versa.
cluster_Amplitude file is also saved with amp value.
This bug makes several issues in phy2 which are waveform, cluster scatter, amplitude view.

### Reproduce the bug:

```python
Always occurs.
```

### Version information:

I used Ubunut 20.04 and CUDA 11.8 in both kilosorts.
Kilosort 2.5 ran in MATLAB R2023b and Kilosort 4 ran in 3.9.19.

**Comment by jacobpennington** [comment]
Hello, thanks for reporting this. Unfortunately it was not a simple case of variables being swapped, "amp" is actually generated by Phy and not something that we report directly. We've made some changes to the way templates are saved, and how cluster_Amplitudes are calculated, that should make those values comparable to previous versions. The changes are in #646 pending review, if you want to try it out with your data. Otherwise they'll probably be live in a few days unless we find other problems with it.

**Comment by jacobpennington** [comment]
Okay, this has been resolved with the changes pushed today, I'll add it to a new pip version soon.

For @hoyeon912 and anyone else that comes across this, please note that the values in the 'amp' and 'Amplitude' columns in Phy will likely not match previous versions, but we've updated them in the way that makes the most sense to us (and which fixes a related issue with templates and waveforms not having the same scale in Phy). The 'Amplitudes' column (computed by us) is the norm of the whitened templates. The 'amp' column (computed by Phy, we don't control this) is the largest `max - min` across channels for the un-whitened templates.
