### ISSUE TITLE
BUG: Error when using --filename in command line

### ISSUE THREAD

**Issue by AntonioST** [MouseLand/Kilosort#651]
### Describe the issue:

Starting a kilosort application with command-line option `--filename` raise an error.

### Reproduce the bug:

in command line

```bash
python -m kilosort --filename recording.imec0.ap.bin
```

### Error message:

```shell
Traceback (most recent call last):
  File ".../python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File ".../kilosort/__main__.py", line 10, in <module>
    launcher(args.filename)
  File ".../kilosort/gui/launch.py", line 49, in launcher
    kilosort_gui = KiloSortGUI(kilosort_application, filename=filename)
  File ".../kilosort/gui/main.py", line 97, in __init__
    self.settings_box = SettingsBox(self)
  File ".../kilosort/gui/settings_box.py", line 37, in __init__
    self.data_file_path = self.data_file_path.resolve()
AttributeError: 'str' object has no attribute 'resolve'
```

### Version information:

latest kilosort version (commit hash 4b4dc75)

**Comment by jacobpennington** [comment]
Hello @AntonioST,

Thanks for catching this, I just pushed a fix. I'll just add that we haven't updated the command line options after making a lot of changes to the GUI, so you might run into some other minor bugs. If you don't want to deal with that, I'd recommend skipping the --filename option for now and just choosing the file in the GUI (you can paste in the path instead of using the file dialog, if you don't like using that).
