### ISSUE TITLE
Problems with 4-shanks probes

### ISSUE THREAD

**Issue by Lorena-J** [MouseLand/Kilosort#652]
### Describe the issue:

Hi! I have a problem with the way kilosort shows me the schema of the probe, i'm trying to do the sorting with a 4-shank probe, all the coordenates are revised and ok, but when i plot the probe view is not the same shape than my probe. 
<img width="405" alt="Captura de pantalla 2024-04-02 a las 14 25 39" src="https://github.com/cortex-lab/KiloSort/assets/146965710/c4d6ae96-d316-417f-a74c-2e60b37102ee"> 
(This is my probe loaded with the jupyter notebook)
<img width="74" alt="Captura de pantalla 2024-04-02 a las 14 26 28" src="https://github.com/cortex-lab/KiloSort/assets/146965710/0513e7ee-4fb0-46c4-8397-ce5411c93196"> 
this is how the probe is seen in kilosort4)
[Páginas desdeCambridge-NeuroTech-Product-Catalog.pdf](https://github.com/cortex-lab/KiloSort/files/14836597/Paginas.desdeCambridge-NeuroTech-Product-Catalog.pdf) 
(and this is my real probe)
thank's for help!!

**Comment by jacobpennington** [comment]
The visualization in the GUI is not exactly proportional even with single-shank probes, it just tries to use all the available. So, a short and wide layout like yours is going to look stretched like that since the viewing box of the plot assumes the probe is going to be tall and narrow (like single-shank neuropixels probes). We're planning to add scale bars in the future, or possibly add an option to switch between representations.

Since you mentioned you're using a 4-shank probe though, you should also take a look here: [https://kilosort.readthedocs.io/en/latest/multi_shank.html](https://kilosort.readthedocs.io/en/latest/multi_shank.html). In short, until we implement multi-shank sorting you should artificially stack the shanks in your probe layout so form a single shank.

**Comment by Lorena-J** [comment]
Thanks for the link, I'll take a look at it so I can set up my 4 shanks probe. Thank you very much for the quick response!

**Comment by jacobpennington** [comment]
FYI, the version I just pushed today (4.0.4) should be able to handle multi-shank probes without artifically stacking them, if you want to try that out. If you do, please let us know how it goes! There is also an option in the GUI now to show a physically proportional view of the probe.
