### ISSUE TITLE
Comparison of KS2.5 and KS4 parameters

### ISSUE THREAD

**Issue by Djoels** [MouseLand/Kilosort#689]
### Describe the issue:

In starting to pick up KS4 we are wondering how the old parameters of KS2.5 relate to the new.

Is there some sort of a migration guide available for this?

Very specifically I'm unsure on 
* the meaning of the new Th (single channel) parameter (set to 6 by default): is this related to the old spkTh parameter (-6 by default)?
* what has happened to the ThPre parameter (threshold crossings for pre-clustering (in PCA projection space). has this parameter now been hardcoded, or does this one relate to Th (single channel) or is this concept obsolete now?
* minimum firing rate (minFR): this is no longer is used in KS4?
* nskip parameter used in KS2.5 (how many batches to skip for determining spike PC’s) no longer exists under the same meaning in KS4?

Thank you in advance, we're very excited about the KS4 developments!

**Comment by jacobpennington** [comment]
I'll let @marius10p answer your question since I'm not too familiar with all the parameters from previous versions. However, please note that even in cases where you see a direct parallel in the parameters between versions, you should still start by using the default values for Kilosort4. Many of the parameters, like the spike detection thresholds, have the same meaning but are implemented differently, so using the same values you used before may not work well.

**Comment by marius10p** [comment]
hi, I think it's a good idea to forget everything you know from Kilosort 2.5 and start over with Kilosort4 because many things are new. Unlike previous versions, now we actually have a paper with detailed descriptions of parameters, so I encourage you to dig into that to understand the meanings of different parameters. The first place to start is the [parameters.py](https://github.com/MouseLand/Kilosort/blob/main/kilosort/parameters.py) file which has all the parameters and their descriptions.
