### ISSUE TITLE
How long are sorts approximately supposed to take? Do we expect KS4 to take much longer than KS3?

### ISSUE THREAD

**Issue by DanEgert** [MouseLand/Kilosort#692]
### Describe the issue:

My recordings are from a 256ch array and 7hrs long. KS3 takes less than a day to sort, but KS4 doesn't complete within 5 days. If I only sort a 1hr cut from this recording KS4 completes within one day. 

Is that what we'd expect? Any recommendation on how to speed up the KS4 sort?

I'm running it on a 3GHz 40 core Xenon CPU with 256GB RAM, SATA Samsung Evo 870 SSD and MSI 4070ti RTX GPU 
KS4 v 4.0.7, device='cuda', all standard parameters

Thanks for any clue

**Comment by jacobpennington** [comment]
Hello,

No, this is far longer than expected and in general Kilosort4 has been faster than Kilosort3. Can you please share the probe layout you're using, and a screenshot of the UI with the data and parameters visible? Including the "extra settings" window, if you changed any values there.

**Comment by DanEgert** [comment]
Thanks for your reply. Glad to hear this should run faster. :)

My vertical electrode pitch is 30um, my horizontal electrode pitch is 100um. There's 8 electrodes on one shank and 32 shanks.
The recording has 256ch, and 191 are included in my probe layout.

I attached screen shot showing the KS4 GUI with my channel map loaded, and the Jupyter lines I use to run it. It shows that for a 2.5hr recording it uses 4500 iterations to compute universal templates, and each iteration takes 12.2s. That by itself is 15hrs.

![ks4-gui](https://github.com/MouseLand/Kilosort/assets/27200250/89f6cf66-89c9-4da4-9a15-cfc38f9c93fb)
![jupyter](https://github.com/MouseLand/Kilosort/assets/27200250/e7ed35ed-9e79-441a-9a11-46bde6a33b05)

**Comment by jacobpennington** [comment]
Okay, a couple things to try:

1) You should turn off drift correction (set `nblocks = 0`). With only 8 electrodes on each shank it's not going to work very well, and could be causing problems due to a noisy estimate.

2) Set `dmin = 30` and `dminx = 100` (i.e. equal to the vertical and horizontal pitches, respectively). This will reduce the number of templates used, currently it looks like there are far more than necessary. I would also recommend setting `max_channel_distance = 30` for the same reason, if the contacts are always in a single column (it looks like that's the case, but hard to tell for sure from that picture). For a longer recording like this, that should help with sorting time and we've found that a single column of templates is generally sufficient for a shank with a single column of contacts.

**Comment by DanEgert** [comment]
![ks4 gui new probe](https://github.com/MouseLand/Kilosort/assets/27200250/15b5c8a3-0258-4878-aa71-cc3502550fcc)

This has worked great, thanks Jacob! The sort now indeed takes about as long as the recording time and the number of clusters found hasn't changed much.

Just to make sure - I do expect some, albeit few neurons to have spikes on adjacent shanks. With these settings, they still wouldn't get logged as separate clusters given that their timestamps mostly match, right?

And yes, the contacts are always in a single column with this probe design, but the shanks can be as close as 66um in a related design, so the array should have overlapping recordings between shanks. Please let me know if I should adjust a parameter to account for this. I'm a bit fuzzy on what max_channel_distance would do with the sort.

Thanks again,
Cheers,
Dan

**Comment by jacobpennington** [comment]
To your first question, no part of the pipeline explicitly uses shank index, so yes it should be possible for spikes on adjacent shanks from the same neuron to be assigned to one cluster. They would be assigned to separate clusters initially because of the placement of the grouping centers, but there's no reason those clusters couldn't merge in the subsequent step.

To your second question, if you expect to sometimes detect neurons that are between shanks, then the current settings look fine. If you don't expect anything between shanks (like when they're 100um apart), setting `max_channel_distance` can get rid of the template placements that are between shanks (which are useless if the contacts are too far apart to detect any spikes from those areas). `max_channel_distance = 30`, for example, means "don't use templates that are more than 30um from at least one contact."

**Comment by jacobpennington** [comment]
It sounds like this was resolved, so I'm going to close this for now. If you have any more questions please let us know!
