### ISSUE TITLE
Sorting with probes with no geometry suggestion request

### ISSUE THREAD

**Issue by ryoiwata** [MouseLand/Kilosort#694]
### Describe the issue:

Hey all!

Thank you to everyone for helping make such a powerful tool in neuroscience! We have been starting to familiarize ourselves with Kilosort and wanted some suggestions. 

We are currently trying to spike sort electrophysiology data from multi-site chronic electrodes. We are using kilosort 4.0.5 and spike interface 0.100.6. There is no geometry to our probes because we are using a microwire bundle that one of my labmates have created. For the probe, we created an artificial shape. 

First, is it possible to spikesort without taking geometry into account? We were setting the `nearest_chans` variable to be the total number of channels, but wasn't sure if there were any other settings that could be changed.

Second, what options are there to limit the spike sorting to be from a select number of channels only. Since some of our channel layout is different across electrodes, we were hoping that there would be ways to exclude channels during the sorting or to ignore units that came from the after.

Our current settings/pipeline are:

```
        trodes_recording = se.read_spikegadgets(recording_file, stream_id="trodes")       
        trodes_recording = trodes_recording.set_probes(probe_object)
        
        clipped_recording: si.BaseRecording = sp.resample(trodes_recording, resample_rate=20000, dtype=np.float32)

        child_spikesorting_output_directory = os.path.join(recording_output_directory,"ss_output")
               
        start = time.time()
        # Make sure the recording is preprocessed appropriately
        # lazy preprocessing
        print("Running bandpass filter")
        recording_filtered = sp.bandpass_filter(trodes_recording, freq_min=300, freq_max=6000, dtype=np.float32)

        print("Running whitening")
        recording_preprocessed: si.BaseRecording = sp.whiten(recording_filtered, dtype=np.float32)
                
        print("Spike sorting")
        spike_sorted_object = ss.run_sorter(sorter_name="kilosort4", 
                                            recording=clipped_recording,
                                            skip_kilosort_preprocessing=False,
                                            do_CAR=False,
                                            do_correction=False,
                                            nearest_chans=32,
                                            nt= 41,
                                            Th_universal = 9 + 2,
                                            Th_learned = 8 + 2,
                                            output_folder=child_spikesorting_output_directory
                                            )
```

Thanks again for any help and wishing everyone a wonderful weekend!

**Comment by jacobpennington** [comment]
Hello @ryoiwata,

We do not offer any support for SpikeInterface, so if you need any help with the code you've shown you will need to ask their team about that.

As for sorting without using the probe geoemetry, there is no simple way to do that. However, setting `nearest_chans = 1` (not total channel count) would make sense. I would also try using `nearest_templates = 1` and `max_channel_distance = 1`, which will limit universal template placement so that there is only a single template placed exactly on each contact assuming your artificial geometry is something simple like a single column of channels.

Currently, there is no option to specify disconnected/unused channels. You would need to create a new probe layout with those channels excluded. Adding this feature is on the todo-list (#666), I just haven't gotten to it yet.

**Comment by jacobpennington** [comment]
I'll close this for now since it seems like everything was answered, if you need additional help please let us know and we can re-open this.

**Comment by hiroyukioya** [comment]
Hi 
One more question: In this case, do you have any recommendation on whitening parameters?

**Comment by jacobpennington** [comment]
I would recommend using the default parameters.
