### ISSUE TITLE
How to adjust parameters to improve sorting results?

### ISSUE THREAD

**Issue by StellaFFF** [MouseLand/Kilosort#706]
### Describe the issue:

Hi there!

I am using Kilosort4 for spike sorting with 4 tetrodes (16 channels) on a 30-minute recording. After analysis, I encountered two issues:

1. Similar to issue #664, I am experiencing misaligned spikes.
![902679b6492231215f7c158b644e090](https://github.com/MouseLand/Kilosort/assets/162967189/18b39565-91f8-4519-a770-944cda98eea5)

2. The same spike is being dispersed into different units.
![d0b64cdbd1917037a481caa41730edb](https://github.com/MouseLand/Kilosort/assets/162967189/b062349d-37f3-4304-810e-0b6c1bfa6d21)

3. There are five channels with spikes that look very similar. Is that proper that I merge them?
![image](https://github.com/MouseLand/Kilosort/assets/162967189/34e9ff7b-e96f-47cf-9a53-903627345bc5)

4. The template waveform and the mean waveform are very different:
![image](https://github.com/MouseLand/Kilosort/assets/162967189/c96e4571-20b0-4b1e-9de3-ed56da720c04)
![image](https://github.com/MouseLand/Kilosort/assets/162967189/c0f8e404-0903-44e3-8f92-1be18da1aeae)
![image](https://github.com/MouseLand/Kilosort/assets/162967189/4d8a105a-f16e-4e6b-9077-bfd07caf25c7)

Could you please help me with adjusting the parameters to achieve better spike sorting results? Thank you!
![image](https://github.com/MouseLand/Kilosort/assets/162967189/be1cefc0-4a7e-49b4-8cc8-601fcb51e1bf)
![image](https://github.com/MouseLand/Kilosort/assets/162967189/b182ff9b-9248-4f81-b730-34f46f0ea008)

**Comment by jacobpennington** [comment]
For 1: there are no settings to change for this problem, @marius10p  is working on a fix.
For 2 and 3: I'll let @marius10p  answer those.
For 4: Which version of Kilosort4 are you using? We changed the way template amplitudes are computed in 4.0.7, which should have fixed this problem.

**Comment by jacobpennington** [comment]
After discussing with Marius:

2) Just clarifying, that does not suggest the same *spike* is being assigned to multiple units, just spikes with a similar waveform. Given that these are all from MUA units with low spike count, it's not that surprising and the "true" cluster for that waveform is probably showing up elsewhere. In fact, it looks like that's what you're seeing in 3).

3) Broadly speaking, yes it looks like some of those can be merged. Specifically all of them except the unit colored blue, since that one does not have a clear refractory period for the CCGs (but the other 4 do).

There aren't any settings to tweak to "fix" this, there are always going to be cases where merging doesn't work well. For example, here it looks like something happened during the recording around t=1000 that caused a big change in amplitudes, which can mess up the clustering as well - especially for probes with low channel count like this, where drift correction is not feasible.
