### ISSUE TITLE
FEATURE: Applying Kilosort to Microwires in Human Hybrid Electrodes

### ISSUE THREAD

**Issue by XiaoyuZeng** [MouseLand/Kilosort#745]
### Feature you'd like to see:

Hi All,

I'd like to express my sincere gratitude for developing Kilosort. It's an incredibly powerful tool that has revolutionized spike sorting.

I'm reaching out regarding the **application of Kilosort to spike sorting for neuronal activity data recorded from microwires in human hybrid electrodes**. These microwires in hybrid electrodes are the most frequently used approach to record neuronal activity in the human brain. **Adapting Kilosort to such data could significantly enhance its applicability in the field of cognitive neuroscience.**

![image](https://github.com/user-attachments/assets/e3d1d576-2be5-402d-ac8f-86ce3f768152)

I've noticed that the Colab notebook primarily focuses on Neuropixels. Given the differences between Neuropixels and human hybrid electrodes, I'm seeking guidance on the necessary adjustments for human hybrid electrode data.

Specifically:

1. Is Kilosort compatible with data from human hybrid electrodes?

2. What modifications to the code would be necessary to apply Kilosort to microelectrodes in human hybrid electrodes? A key difference is that these microelectrodes lack a predefined electrode array geometry like Neuropixels.

3. Are there any recommended parameter optimizations for this type of data?

4. Are there any existing resources, examples, or case studies of Kilosort being used with human hybrid electrode data?

5. What potential challenges should we be aware of when adapting Kilosort for this purpose?

Thank you for your time and expertise. I'm looking forward to your response and any assistance you can provide.

Best regards,

**Comment by jacobpennington** [comment]
As for your first three questions:

I can't think of any specific code reasons why Kilosort4 would not work with this data. It sounds like you're saying the electrodes are essentially all independent from one another, in which case you would use a sort of "dummy" probe to specify the geometry. For example, pretending that all electrodes are on a single shank with 100um spacing so that they are far enough apart that they will effectively be sorted separately.

From that point, you should just try sorting the data with default parameters and see if you run into any errors or get reasonable results when viewed in Phy. Some parameters you might end up needing to tweak if that doesn't work would be:
1) `dmin = 200` (or double whatever spacing you use for your fake probe) so that templates are not placed at the mid-points between contacts.
2) `nearest_chans = 3` and `nearest_templates = 3`, so that resources aren't wasted on "neighboring" channels or templates that aren't actually anywhere near each other.

@marius10p might have more information about 4 and 5.

**Comment by XiaoyuZeng** [comment]
> As for your first three questions:
> 
> I can't think of any specific code reasons why Kilosort4 would not work with this data. It sounds like you're saying the electrodes are essentially all independent from one another, in which case you would use a sort of "dummy" probe to specify the geometry. For example, pretending that all electrodes are on a single shank with 100um spacing so that they are far enough apart that they will effectively be sorted separately.
> 
> From that point, you should just try sorting the data with default parameters and see if you run into any errors or get reasonable results when viewed in Phy. Some parameters you might end up needing to tweak if that doesn't work would be:
> 
> 1. `dmin = 200` (or double whatever spacing you use for your fake probe) so that templates are not placed at the mid-points between contacts.
> 2. `nearest_chans = 3` and `nearest_templates = 3`, so that resources aren't wasted on "neighboring" channels or templates that aren't actually anywhere near each other.
> 
> @marius10p might have more information about 4 and 5.

Thank you for your reply! Upon further consideration, I realized there's an additional important point I'd like to address: drift correction.

Specifically, I'm curious about should I just turn off drift correction  in Kilosort4 for microwires in human hybrid electrodes?
(https://github.com/MouseLand/Kilosort/issues/433)

**Comment by jacobpennington** [comment]
Yes,  sorry,  I forgot to include that. You should set `nblocks = 0` to
skip drift correction.

**Comment by Nitaym** [comment]
Hey @jacobpennington, thanks for your answer.

I'm trying to use kilosort with a similar electrode with human data, and would like to control how kilosort treats the electrodes. With microwires, we don't know the distance between the electrodes - So treating them as separate electrodes makes sense. 

> 1. `dmin = 200` (or double whatever spacing you use for your fake probe) so that templates are not placed at the mid-points between contacts.

My understanding is that dmin is the *maximum* distance that kilosort will consider for multi-electrodes clustering (i.e. build a template across these channels). If that is the case, shouldn't dmin / dminx be very low? 0 even?


> 2. `nearest_chans = 3` and `nearest_templates = 3`, so that resources aren't wasted on "neighboring" channels or templates that aren't actually anywhere near each other.

Why not set it to 1 (only the current channel)?

Thanks!

**Comment by jacobpennington** [comment]
@Nitaym dmin and dminx control the placement of grid points for universal template positions. They should *always* be set based on the spacing of the contacts on the probe and nothing else. The goal with this kind of probe is just to end up with one template centered on each contact, and using 2x the normal value should accomplish that. They do also affect how many channels are considered at once for clustering, but that's only done to prevent too many spikes being clustered at once for very large probes, to speed up computation.

For `nearest_chans` and `nearest_templates`, 1 is what "makes sense" but using the settings that way is untested since we generally expect to be looking a range of channels and templates. With recent updates you shouldn't even need to set those to a small value anymore, you should sort with default settings and only change them if you encounter errors.
