### ISSUE TITLE
How to create a single channel map

### ISSUE THREAD

**Issue by AidanFishenden** [MouseLand/Kilosort#752]
I am trying to create a single channel map for kilosort 4 using the GUI, since each of my attempts in matlab have resulted in an error stating my connected variable is not valid. Given that this is only one channel, what I am trying to do is label both X and Y as 0, and am putting 0 for the channel map 0 indexed area and leaving the kcoords section blank. This is resulting in an error stating Len() of unsized object. Does anyone know how to create a map with only one channel that Kilosort will accept?

**Comment by jacobpennington** [comment]
@AidanFishenden As for the KS4 GUI, it looks like there's a bug in the way the variables are checked that causes that error if there's only a single value. I'll fix that for the next version release, but in the meantime you can get around it by entering `np.zeros(1)` for xc, yc, and chanMap instead of just the number 0.

For .mat probe files, KS4 also expects a `connected` boolean variable that is True for channels that should be included, and False otherwise. So you would want to add that to your probe as a single `True` value.

**Comment by AidanFishenden** [comment]
Understood, thank you so much!

**Comment by jacobpennington** [comment]
Sorry, just adding onto this after discussing with Marius. There will likely be other errors that come up throughout the sorting pipeline for a single-channel probe, and we're not planning to invest time into supporting sorting single channels. However, you could combine several single-channel recordings into a single file and use an artificial probe geometry (like spacing the channels 100um apart) to sort them simultaneously.

**Comment by holmescharles** [comment]
Follow up question to the previous suggestion: How would you recommend one to combine multiple recordings of different length?

**Comment by jacobpennington** [comment]
You could try padding the ends of the shorter recordings with zeros to make them all the same duration as the longest recording. However, if the differences in duration are large (more than a batch or two) it's possible that will cause problems since there will be large stretches of empty data. So, my suggestion would be to try it that way and if you run into errors then it's likely just not going to work. Kilosort4 was not designed to be used that way.

**Comment by holmescharles** [comment]
Certainly many people using kilosort will at some point record with a single microelectrode. Do you have a recommended alternative spike sorter to use that will work with single channels and give results similar to kilosort?

Do you know what would happen if the data were replaced with multiple copies of the same channel? I.e., take a single signal and stack them. Would that trick kilosort to work with "single channel data"? 

Thanks!

**Comment by jacobpennington** [comment]
My first recommendation would be to just try it and see. At least one other user has sorted a recording with only a single channel, and I believe they got it to work. If you want to try other sorters, https://github.com/SpikeInterface/spikeinterface has resources for that.

As for stacking copies of the same channel, I think that's unlikely to work well. But again, try it and see.

**Comment by holmescharles** [comment]
Thanks for the info. Do you know if that user posted a github issue? If so, I will go look for it.

**Comment by jacobpennington** [comment]
Yes, they posted an issue.
