### ISSUE TITLE
Probe layout for Neuropixels 1.0

### ISSUE THREAD

**Issue by PiezaKake** [MouseLand/Kilosort#795]
Hi, I am not sure which one is the correct probe layout for Neuropixels 1.0 recordings. Would that be neuropixPhase3B2_kilosortChanMap.mat?

**Comment by jacobpennington** [comment]
It depends on which NP1 probe you're using, and how you configured it. Both `neuropixPhase3B1_kilosortChanMap.mat` and `neuropixPhase3B2_kilosortChanMap.mat` are Neuropixels 1 probes, and you can see the channel layout in the GUI by selecting them and clicking the "preview probe" button. However, the layout we use for those defaults may or may not match your probe, since users can change which contacts are active for Neuropixels probes.

If you're unsure of your probe layout, you should use this tool to generate your own probe file from the information exported by SpikeGLX (or another tool if you recorded with something else): https://github.com/jenniferColonell/SGLXMetaToCoords

**Comment by PiezaKake** [comment]
Thank you for the prompt reply. I recorded with Open Ephys and used the default electrode preset Bank A, which is 384 successive electrodes starting from the tip of the shank.

**Comment by jacobpennington** [comment]
I'm not familiar with the Open Ephys presets, so I don't know if that matches up with either of our default NP1 layouts. You would have to figure out that part on your own, either from Open Ephys documentation or from the files it created when recording. It does look like the Open Ephys probe GUI has an option to export to a ProbeInterface-formatted json file. Kilosort4 won't read those directly, but you could save to that format and then use ProbeInterface to save it as a .prb file, which Kilosort4 can read.
https://probeinterface.readthedocs.io/en/main/examples/ex_06_import_export_to_file.html
