### ISSUE TITLE
OSerror when trying save preprocessed copy in kilosort4

### ISSUE THREAD

**Issue by kingsEffy** [MouseLand/Kilosort#805]
### Describe the issue:

Hi,
Have anyone experienced this error in kilosrt4 GUI when trying to save preprocessed dat copy? We are using standard parameter settings. And there i8s no such error before when we did not select save copy.

![Screenshot 2024-10-24 155635](https://github.com/user-attachments/assets/647a763e-599d-4f1b-a60a-0920f05706c0)

### Version information:

Kilosort 4: Kilosort version 4.0.15

**Comment by jacobpennington** [comment]
Can you please attach a screenshot of what the Kilosort4 GUI looks like after loading the data?
You should also try updating to the latest version of Kilosort, v4.0.19.

**Comment by Kun-Ming** [comment]
Seems like `results_dir / 'temp_wh.dat'` did not act correctly so `np.memmap` has an invalid argument. Do you assigned `results_dir` on GUI? And could you please check if the `results_dir` exist? According to https://github.com/MouseLand/Kilosort/blob/v4.0.15/kilosort/gui/sorter.py#L46, if `self.results_directory` has a meaningful value, then the `result_dir` should exist on disk. `result_dir` had been assigned on https://github.com/MouseLand/Kilosort/blob/v4.0.15/kilosort/gui/main.py#L500. And I don't think this issue is related to version cause all related code remains unchanged from 4.0.15 to 4.0.19.

**Comment by jacobpennington** [comment]
Can you please attach a screenshot of what the Kilosort4 GUI looks like after loading the data?
