### ISSUE TITLE
Batch size

### ISSUE THREAD

**Issue by hiroyukioya** [MouseLand/Kilosort#813]
### Describe the issue:

not an issue, but if I have recording of duration of 5min, can we use batch size of 5min instead of 2sec?  What is your expectation?

### Version information:

v 4.0.12

**Comment by jacobpennington** [comment]
Depending on how many channels you're using, the sorting is likely to fail due to insufficient memory. Sorting is broken up into small batches for more efficient processing, and dramatically increasing the batch size will undo that. As for how that might affect the actual sorting results (assuming you're able to run it), @marius10p would be a better person to answer that.

**Comment by marius10p** [comment]
It means you won't get good drift correction anymore, since there is one drift per batch, and yes, it will probably run out of GPU RAM too. The edges of the batch should be dealt with correctly by Kilosort4 if that is what you are worried about.

**Comment by hiroyukioya** [comment]
Thank you. That is a great info. 
I could run it with 5 min batch size (we have small channel count and drift estimation is off).  In terms of sorting results, what do you expect the effect of batch size (better for longer batch)?

**Comment by jacobpennington** [comment]
Aside from drift correction not working as well, our advice would be to just try it if you think it would be helpful, with the understanding that that parameter was intended to be used on the order of seconds not minutes. If you encounter errors, please let us know.

**Comment by hiroyukioya** [comment]
Yes, thanks!
