### ISSUE TITLE
BUG: Excessive RAM usage on large file

### ISSUE THREAD

**Issue by VValentina86** [MouseLand/Kilosort#823]
### Describe the issue:

Hi, I have a 2 hr recording of 384 channels (1 probe, ~200GB file size). I'm trying to run `run_kilosort` with this file (using `DEFAULT_SETTINGS`). During the "Computing drift correction" step ("Detecting spikes" sub-step), the (CPU) RAM usage grows steadily up to ~120 GB at 40% progress in the routine. Can you please help me understand if there's a memory link or why so much is being held in memory and not released? 

I quickly tried to call `run_kilosort` with `clear_cache=True`, but the high RAM usage persisted. Even a smaller recording (~20 GB) used ~80 GB RAM, so the file size doesn't seem to be the issue.

I've seen [this comment](https://github.com/MouseLand/Kilosort/issues/766#issuecomment-2479676663) in #766, but unless `run_kilosort` is calling `spikeinterface` internally, I'm not using `spikeinterface`. Based on [this other comment](https://github.com/MouseLand/Kilosort/issues/766#issuecomment-2363479670) in that thread, I'm happy to change the data `dtype` if that prevents high memory usage, though I'm not sure where to change that when using `run_kilosort`.  

(Tagging my collaborator: @jeffjennings)

### Reproduce the bug:

My full script is:

```
from kilosort import run_kilosort, DEFAULT_SETTINGS
from kilosort.utils import download_probes
download_probes()

settings = DEFAULT_SETTINGS
settings['n_chan_bin'] = 385
data_file = <path>
probe_name = 'neuropixPhase3B2_kilosortChanMap.mat'
clear_cache = False

ops, st, clu, tF, Wall, similar_templates, is_ref, est_contam_rate, kept_spikes = \
    run_kilosort(
        settings=settings, 
        filename=data_file,
        probe_name=probe_name, 
        clear_cache=clear_cache
        )
```

### Version information:

Python 3.11.10
Kilosort 4.0.20 (using CUDA)
Windows 10 (GPU: Nvidia RTX 3090)
CUDA 11.8.89

**Comment by jacobpennington** [comment]
@VValentina86 Please start by uploading `kilosort4.log` from the results directory.

As for changing the data dtype, you should only do that if your data has a different dtype than the default (int16). Since you're recording with Neuropixels, that should only be the case if you're doing some of your own preprocessing prior to running Kilosort4 that would change the dtype.

**Comment by katjaReinhard** [comment]
sorry for reopening this, but I'm running into a comparable issue where RAM gets maxed out at the template matching step. I'm attaching the log and I've had the exact same issue when running it directly on the .bin file from spikeGlx, i.e. it isn't because of the data type. This is a ~3.5h long recording with 1 NPX probe (384 channels) and I have 32 GB RAM with 20 cores and a GeForce RTX3060 12 GB graphic card. I don't have any GPU issues, but during the clustering, RAM usage ramps up quickly and either there or during template matching it maxes out the 32 GB and crashes. Slightly shorter recordings (~3h) are still sortable, but after that it breaks down. I'm surprised because based on the hardware recommendations, 32 GB should be plenty for up to ~6h of recordings and I'm also worried as we plan to have longer recordings in the near future. any advice would be highly appreciated.

[kilosort4.log](https://github.com/user-attachments/files/21136443/kilosort4.log)

**Comment by marius10p** [comment]
Hi Katja, @jacobpennington has been steadily improving resource utilization, but I recommend just upgrading your RAM, since right now it's relatively cheap, and it will be worth it in the long term if you plan to sort longer recordings.

**Comment by jacobpennington** [comment]
@katjaReinhard `NTbuff` is not an exposed parameter, it's set by KS4 based on `batch_size` and `nt` (number of waveform samples). By default `batch_size` is 60000, or 2 seconds of data for a 30KHz recording. However, it's unlikely that will help in this case. Based on when the error is happening, you're most likely running out of memory as more spikes are detected and their features get added to a few variables that continue to grow as needed. Those variables do not depend on batch size.

The hardware recommendations are just a ballpark figure, the actual needs are going to be different for each recording based on the number of spikes present. It's also affected by the amount of memory used up by other processes on the machine, if any. The log you attached appears to have reached the limit at around 15GB of memory, for example, so there may have been a significant chunk used up by other software.

That said, I'll update the recommendations with more detailed information.

**Comment by katjaReinhard** [comment]
@jacobpennington thanks for the response. yes, the log says 15GB but I watched the process and saw a sudden increase to ~30GB right when it crashed. there's nothing else running on the machine. we'll certainly upgrade our computer, I just wanted to make sure there isn't anything else we could do to improve the performance and enable sorting of our current data.
