### ISSUE TITLE
Advice Needed on Artifact Threshold Settings for Optogenetics + Recording Experiments

### ISSUE THREAD

**Issue by EMerinoM14** [MouseLand/Kilosort#828]
Hi everyone,

I am currently conducting optogenetics and recording experiments with my animals. However, I’ve been encountering significant artifacts during stimulation, which are interfering with spike sorting (with kilosort4) accuracy.

While reviewing the forum, I noticed that in the extra settings, the first option allows you to set a threshold for artifacts. At the moment, I have it set to the default value (Inf), but I’m wondering if there’s a recommended value that might help reduce these issues.

Any advice or guidance on how to configure this setting effectively would be greatly appreciated.

Best regards,

**Comment by puterd** [comment]
Hi

I am experiencing a similar problem. One approach might be to use spike interface and pre process the data using the in built stimulus arteface removal methods (see bottom of this page: https://spikeinterface.readthedocs.io/en/0.96.1/modules/preprocessing/plot_1_preprocessing.html). 

As for directly using kilosort4, I would recommend doing some analysis of the stimulus artefacts and setting the value based on that. I believe that the removal procedures are intentionally modular and not predefined in this library because the artefacts end up being very different across different setups,etc (see #102). 

Best wishes

**Comment by jacobpennington** [comment]
@EMerinoM14 My advice would be the same as @puterd - you'll have to look at your data to determine what range of values indicate the presence of an artifact. For example, if your data is normally in the range (-100, 100) but occasionally spikes to +/- 1000 when the artifacts occur, you could try setting `artifact_threshold=800`. However, please keep in mind that this will simply zero out any batches containing at least one absolute value greater than that number. There may be more sophisticated approaches available for opto stim artifacts that you could apply prior to sorting, but that's outside the scope of Kilosort.

**Comment by EMerinoM14** [comment]
@jacobpennington What are the units in which the threshold is measured, in standard deviations?

**Comment by jacobpennington** [comment]
It's whatever units your data is in. There is nothing complicated
happening. It's just checking the equivalent of `max(abs(data)) >=
threshold` for each batch.
